# Generated by Django 5.0.1 on 2024-02-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='relpy',
            new_name='reply',
        ),
    ]
